---
- hosts: localhost
  gather_facts: false
  vars_files:
    - data-var.yaml
  tasks:
    #- set_fact:
    #    Company: "{{ Company }}"
    - name: Print Data
      debug:
        msg: "{{ Company }}"
      when: a is defined
    
    - name: Print Data 2
      debug:
        msg: "{{ Company['Country']['states'][0]['employee'][item]['payroll_emp']['id'] }}" 
      with_items: "{{ Company | json_query('Country.states[0].employee')  }}"

    - name: Set Data
      set_fact:
  
        Company: "{{ Company | combine( {'Country':{'states':[{'employee':{'Internal_1':{'payroll_emp':{'id':3000}}}}]}}, recursive=True, list_merge='append_rp' ) }}"


    - name: Print Data
      debug:
        msg: "{{ Company }}"
      #when: a is defined
